### ISSUE TITLE
Interface loads but remains blank

### ISSUE THREAD

**Issue by jmm** [node-inspector/node-inspector#671]
Possibly related to #657. node-inspector used to work great but now it's doing this thing most of the time where the interface loads but does nothing, remains completely blank. My environment:

node 0.10.32 / node-inspector 10.0.0 / 10.0.1 running on Ubuntu 12.04.
Debugging remotely from Windows 7 x64 / Chrome 42 on different physical machine on same local network.
```sh
node-debug --debug-brk --web-host=example.com script.js
```

Since I updated Chrome to v41 it started exhibiting frequent DNS failures and I recently ran Fiddler (debugging proxy) to see if it could reveal anything, and just running it seems to sidestep the Chrome DNS failures, so I've been running it since. I mention it in case it's relevant somehow, but as I said the interface loads, just nothing within it. And I believe I've had it function normally at least once with Fiddler running.

I don't know if it's relevant, but I'm also getting this in Chrome console:
```
Assertion failed: Unknown experiment canvasInspection
  Runtime._assert @ Runtime.js:358
  Runtime.ExperimentsSupport._checkExperiment @ Runtime.js:953
  Runtime.ExperimentsSupport.isEnabled @ Runtime.js:894
  WebInspector.ProfileTypeRegistry @ ProfileTypeRegistry.js:19
  (anonymous function) @ ProfileTypeRegistry.js:43
  evaluateScript @ Runtime.js:153
  scriptSourceLoaded @ Runtime.js:136
```

**Comment by jmm** [comment]
@3y3 I'm working on getting the screenshot you requested in #657, and just now it actually worked, with `fiddler` running. I did get this in Chrome console:

```
Assertion failed: Unknown experiment canvasInspection
  Runtime._assert @ Runtime.js:358

Protocol Error: Invalid type of argument 'securityOrigin' for method 'IndexedDB.requestDatabaseNames' call. It must be 'string' but it is 'undefined'.
  onError @ :8080/sdk/InspectorBackend.js:884
```

**Comment by 3y3** [comment]
```
Assertion failed: Unknown experiment canvasInspection
  Runtime._assert @ Runtime.js:358

Protocol Error: Invalid type of argument 'securityOrigin' for method 'IndexedDB.requestDatabaseNames' call. It must be 'string' but it is 'undefined'.
  onError @ :8080/sdk/InspectorBackend.js:884
```
This is expected behavior. Inspector can works with this two errors.

So, do you have a working state?

**Comment by jmm** [comment]
> This is expected behavior. Inspector can works with this two errors.

Ok, thanks.

> So, do you have a working state?

I do at the moment, but I don't expect it to be smooth sailing.

So if my actual command is:

```sh
$ node-debug --debug-brk --web-host=example.com script.js
```

Is this the correct way to generate a debug log?:

```sh
$ DEBUG=node-inspector* DEBUG_FD=3 node-debug --debug-brk --web-host=example.com script.js 3> garbage.log
```

**Comment by 3y3** [comment]
`$ DEBUG=node-inspector:* DEBUG_FD=3 node-debug --debug-brk --web-host=example.com script.js 3> garbage.log` (missed colon)

I'm not sure what this will work as expected, because `node-debug` command mute all output from node-inspector itself.
```
$ DEBUG="node-inspector:*" DEBUG_FD=3
$ node-inspector --web-host=example.com 3> garbage.log
$ node --debug-brk script.js
```
Will work fine. But if your solution works, I'll add it to wiki page.

**Comment by jmm** [comment]
> (missed colon)

Ok, thanks -- that was actually copy and paste from the wiki page you linked me to.

> I'm not sure what this will work as expected, because `node-debug` command mute all output from node-inspector itself.

Oh ok.

> But if your solution works, I'll add it to wiki page.

I imagine it's only a matter of time before I run into the problem again and I'll try it then.

> ...Will work fine.

Ok thanks, I'll try that if the other way doesn't work. Is it possible to do it that way but do the first two lines as one so those environment variables aren't changed for the whole env?

**Comment by 3y3** [comment]
> Is it possible to do it that way but do the first two lines as one so those environment variables aren't changed for the whole env?

Yes, sure! This is my mistake.

**Comment by 3y3** [comment]
Is this issue solved?

**Comment by aldendaniels** [comment]
I'm encountering this same behavior on a mac.

**Comment by jmm** [comment]
@3y3 I doubt it's actually solved -- I expect it to reoccur. If you want I'll close the issue and re-open it if / when it reoccurs.

**Comment by jmm** [comment]
@3y3 I just tried it again for the first time since my last post here and it didn't work again. I was about to post and decided to change the log file name in my shell command just for aesthetics of what I post and decided to try it one more time after doing that, and then it started working. It's very hit or miss. This is the command I was running

```sh
$ DEBUG="node-inspector:*" DEBUG_FD=3 node-inspector --web-host=example.com 3> node-inspector.log &
$ node --debug-brk script.js
```

And I was just getting a `0` length `node-inspector.log` file.

**Comment by jmm** [comment]
It's back to not working. It looks like the log fills up with tons of data when it works. When it doesn't work I get no log output.

**Comment by jmm** [comment]
@3y3 What else can I do to debug this? It's a big problem for me that it's not working.

I tried following [this instruction](https://github.com/node-inspector/node-inspector/wiki/Developer%27s-Guide#reverse-engineering-the-front-end):

> Alternatively, you can enable `this.dumpInspectorProtocolMessages` in `front-end/InspectorBackend.js`.

I had no such file. In `front-end/sdk/InspectorBackend.js` I tried setting `InspectorBackendClass.Options.dumpInspectorProtocolMessages` to `true`. At first it appeared to do nothing, but then I happened to notice something in the browser console. So I tried it again and after about 4 minutes of the interface sitting there doing nothing this output appeared in the console:

```
WebSocket connection to 'ws://example.com:8080/?port=5858' failed: WebSocket opening handshake timed out InspectorBackend.js:666

Event {path: Array[0], cancelBubble: false, returnValue: true, srcElement: WebSocket, defaultPrevented: false…} InspectorBackend.js:698
      bubbles: false
      cancelBubble: false
      cancelable: false
	currentTarget: WebSocket
      defaultPrevented: false
      eventPhase: 0
   path: Array[0]
      returnValue: true
   srcElement: WebSocket
   target: WebSocket
      timeStamp: 1434995638104
      type: "error"
   __proto__: Event
   InspectorBackendClass.WebSocketConnection._onError @ InspectorBackend.js:698
```

**Comment by 3y3** [comment]
You found main problem
```
WebSocket connection to 'ws://example.com:8080/?port=5858' failed: WebSocket opening handshake timed out InspectorBackend.js:666
```
If I understand right in this case you don't receive `Assertion failed: Unknown experiment canvasInspection` anywhere.
Are you using fiddler in this time?

**Comment by jmm** [comment]
@3y3 Thanks again for your help.

> If I understand right in this case you don't receive `Assertion failed: Unknown experiment canvasInspection` anywhere.

No, I *do* still receive that in the browser console. I just stopped mentioning it because you said earlier it's expected. That shows up even before the interface appears. The WebSocket error takes minutes to show up.

> Are you using fiddler in this time?

Yes, fiddler is running.

**Comment by 3y3** [comment]
> No, I do still receive that in the browser console.

Uhm. Now I can't understand how it is possible... In my mind we need an opened websocket to receive this message, but `WebSocket connection to 'ws://example.com:8080/?port=5858' failed: WebSocket opening handshake timed out InspectorBackend.js:666` says that socket fails on handshake...

Can you reproduce this error without fiddler?

**Comment by jmm** [comment]
@3y3 I mostly can't do anything without fiddler, unfortunately. Ever since I updated Chrome to v41 (and now 42) I constantly get these errors:

> This webpage is not available
> `ERR_NAME_NOT_RESOLVED`

I originally ran fiddler to try to debug that and for some reason running fiddler cures it, so I've had to keep it running all the time since then just to get chrome to do DNS resolution. If I disable fiddler Chrome immediately stops resolving DNS.

> says that socket fails on handshake...

What would cause this handshake process to take 4 minutes to time out? That seems excessive.

**Comment by andyburke** [comment]
I'm seeing this trying to debug within a docker container. I'm exposing port 8080 and hitting it, but I just get a blank interface with no sources, etc. Same assertion failure listed above, but nothing else.

**Comment by sadtaco** [comment]
I get the same probelm as @andyburke with 

    Request with id = 10 failed. "ErrorNotConnected: Error: connect ECONNREFUSED. Is node running with --debug port 5858?"

in the console.  I tried "sudo node-inspector && sudo node --debug-brk port 5858 -p 9362" but that does the same.

**Comment by dopesong** [comment]
Got the same problem. Any news on this?

**Comment by meikidd** [comment]
I got the same problem, and I fixed it by install Xcode. 
node-inspector requires node-gyp, and node-gyp requires Xcode.

**Comment by datanotion** [comment]
I just started seeing this same issue - the inspector has worked fine in the past.  Tried latest Chrome and Safari.  This is a Meteor app.

**Comment by ErikBrewster** [comment]
I'm seeing this on Ubuntu 14.04. I was running 14.04 on a VirtualBox VM and it worked. I moved to a fresh Ubuntu machine and it worked for a while until I saw this. The versions that I recorded where things weren't working:
Ubuntu 14.04
node 5.4.1
npm 3.6.0
node-inspector 0.12.5
Chrome 48.0.2564.97 (64-bit)

It worked great on
Ubuntu 14.04
node 0.12.7
npm 2.11.3
node-inspector 0.12.5

But I reverted to those versions on my new system and it still doesn't work.

Of note: I uninstalled NI and ran into the node-gyp stuff that is referenced in issue 785, but the -unsafe-perm didn't help with any of the symptoms in this issue.

**Comment by awolski** [comment]
Same as @datanotion for me. Everything was working fine and now I'm seeing:

`Assertion failed: Unknown experiment canvasInspectionRuntime._assert @ Runtime.js:358`

**Comment by aramk** [comment]
I'm still seeing this on Chrome 55, https://github.com/node-inspector/node-inspector/issues/663 seems related
