### ISSUE TITLE
Detached from the target, websocket_closed, cannot read property ref of undefined (NM[0] is undefined)

### ISSUE THREAD

**Issue by bdanmo** [node-inspector/node-inspector#907]
Doing `node-debug src/app.js`

The immediate feedback from the terminal is :

```
Node Inspector v0.12.8
Visit http://127.0.0.1:8080/?port=5858 to start debugging.
Debugging src/app.js

Debugger listening on [::]:5858
```

After chrome automatically launches and tries to display the page, the chrome windows show this error message:

"Detached from the target. Remote debugging has been terminated with reason: websocket_closed. Please re-attach to the new target."

And the console shows this error:

```
/usr/local/lib/node_modules/node-inspector/lib/InjectorClient.js:111
      cb(error, NM[0].ref);
                     ^

TypeError: Cannot read property 'ref' of undefined
    at InjectorClient.<anonymous> (/usr/local/lib/node_modules/node-inspector/lib/InjectorClient.js:111:22)
    at /usr/local/lib/node_modules/node-inspector/lib/DebuggerClient.js:121:7
    at Object.create.processResponse.value (/usr/local/lib/node_modules/node-inspector/lib/callback.js:23:20)
    at Debugger._processResponse (/usr/local/lib/node_modules/node-inspector/lib/debugger.js:95:21)
    at Protocol.execute (_debugger.js:121:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)

```
I've searched everywhere for a solution to this problem and haven't found one. I hope you can be of assistance!

**Comment by InfinitiesLoop** [comment]
Precisely the same problem I just ran into. Can find nothing.

The only information I have to add is that I used to use node-inspector successfully on node 4. I recently updated to node 6, and this is the first time I've tried to use node-inspector since then.

**Comment by InfinitiesLoop** [comment]
Ah I think this is a dup of:
https://github.com/node-inspector/node-inspector/issues/905

Which seems to indicate it's a problem with node 6.4. Workaround is to downgrade to 6.3.1.

**Comment by bertolo1988** [comment]
+1

**Comment by bdanmo** [comment]
@InfinitiesLoop Right you are, thanks for that!

**Comment by bertolo1988** [comment]
I fixed my problem by downgrading node from 6.4 to 6.3.1.
Why is this closed?

**Comment by superclarkk** [comment]
@bertolo1988 As stated above, this is a duplicate of #905

**Comment by przemuh** [comment]
I can still reproduce it with v6.3.1 :( on linux

```
~$ node-inspector --debug-port 5859 --no-preload
Node Inspector v0.12.8
Visit http://127.0.0.1:8080/?port=5859 to start debugging.
/home/egnyte/.nvm/versions/node/v6.3.1/lib/node_modules/node-inspector/lib/InjectorClient.js:111
      cb(error, NM[0].ref);
                     ^

TypeError: Cannot read property 'ref' of undefined
    at InjectorClient.<anonymous> (/home/egnyte/.nvm/versions/node/v6.3.1/lib/node_modules/node-inspector/lib/InjectorClient.js:111:22)
    at /home/egnyte/.nvm/versions/node/v6.3.1/lib/node_modules/node-inspector/lib/DebuggerClient.js:121:7
    at Object.create.processResponse.value (/home/egnyte/.nvm/versions/node/v6.3.1/lib/node_modules/node-inspector/lib/callback.js:23:20)
    at Debugger._processResponse (/home/egnyte/.nvm/versions/node/v6.3.1/lib/node_modules/node-inspector/lib/debugger.js:95:21)
    at Protocol.execute (_debugger.js:121:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
~$ node --version
v6.3.1

```

**Comment by olavk** [comment]
@przemuh Downgrading to 6.3.1 worked for me on Ubuntu 14.04

**Comment by MasterJames** [comment]
Still broken in 6.5.0!?!  The downgrade to 6.3.1 makes debugging the VM work.
Any idea why it's not working, what can be done, when I/we can debug/use nodejs current version again?

Using the experimental built in node --inspect --debug app.js "Inspect" argument with node-inspector uninstalled, but with this downgrade connects but no source shown from outside of server VM? so that's currently useless.

**Comment by durrellchamorro** [comment]
Downgrading from 6.5.0 to 6.3.1 fixed it for me as well.

**Comment by leisenstein** [comment]
Same issue here on 6.6.0.  I downgraded to 6.3.1 and it works.

**Comment by asdj07** [comment]
I downgraded to 6.2 and it works.......

**Comment by isdenya** [comment]
+

**Comment by boyangwang** [comment]
6.7 and still broken

**Comment by tiagolr** [comment]
Same problem

**Comment by MasterJames** [comment]
Who here has a clue? either where is the problem or who do we tag to get some direction.
My guess is there's a concern that it should work for the most production ready version and the latest greatest is deemed too unstable.
If so I'm thinking how do we have version specific patches or whatever?

**Comment by alienatorZ** [comment]
I downgraded to node 4.6 after not being able to debug, and am having the same issue.

**Comment by alienatorZ** [comment]
In linux I opened with Chrome (not Chromium) and ran node-debug  with sudo and it worked!

**Comment by ughitsaaron** [comment]
Same problem using vs 6.6.0, 6.4.0, 6.3.1

**Comment by jmzwar** [comment]
Same problem with 6.6 downgraded to 6.3.1 and issues seems to disappear, though node-inspector won't load files.

**Comment by dacuotecuo** [comment]
I have the same problem.
nodejs version is v6.8.0, the node-inspector version is v0.12.8 and my OS is macos Sierra(10.12).
how to solve it please?
```
Debugger listening on [::]:5858
/usr/local/lib/node_modules/node-inspector/lib/InjectorClient.js:111
      cb(error, NM[0].ref);
                     ^

TypeError: Cannot read property 'ref' of undefined
    at InjectorClient.<anonymous> (/usr/local/lib/node_modules/node-inspector/lib/InjectorClient.js:111:22)
    at /usr/local/lib/node_modules/node-inspector/lib/DebuggerClient.js:121:7
    at Object.value (/usr/local/lib/node_modules/node-inspector/lib/callback.js:23:20)
    at Debugger._processResponse (/usr/local/lib/node_modules/node-inspector/lib/debugger.js:95:21)
    at Protocol.execute (_debugger.js:121:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```

**Comment by asi-jmasson** [comment]
Same issue with node v6.5.0
can be solved like this :

Edit ...\node_modules\node-inspector\lib\InjectorClient.js file at line 111
	  if(NM.length > 0)
        cb(error, NM[0].ref);

It works

**Comment by dbreese** [comment]
The above will cause the callback to not be invoked. It should be
if (NM.length > 0)
  cb(error, NM[0].ref);
else
  cb(error, null);

**Comment by VladislavAnkudinov** [comment]
same here 
node v6.8.1
Node Inspector v0.12.8

**Comment by stuartZhang** [comment]
I have encountered the same bug.
node v6.8.1
node-inspector v0.12.8

The project dependencies include the below:
    "artikcloud-js": "2.0.2",
    "babel-polyfill": "^6.13.0",
    "body-parser": "^1.13.1",
    "body-parser-xml": "^1.1.0",
    "canvas": "1.5.0",
    "cheerio": "^0.19.0",
    "compression": "^1.6.1",
    "connect": "^3.4.0",
    "connect-busboy": "0.0.2",
    "connect-flash": "^0.1.1",
    "connect-multiparty": "^1.2.5",
    "connect-redis": "^3.1.0",
    "connect-static": "^1.5.0",
    "connect-timeout": "^1.6.2",
    "continuation-local-storage": "^3.1.4",
    "cookie-parser": "^1.3.5",
    "cookie-session": "^1.2.0",
    "cookies": "^0.5.0",
    "cors": "^2.7.1",
    "csurf": "^1.8.3",
    "dateformat": "^1.0.11",
    "ddos": "^0.1.11",
    "domain": "0.0.1",
    "ejs": "^2.3.2",
    "express": "^4.13.0",
    "express-partials": "^0.3.0",
    "express-session": "^1.11.3",
    "follow-redirects": "0.0.7",
    "http-framework": "^1.2.0",
    "js-throttle-debounce": "^0.1.1",
    "keygrip": "^1.0.1",
    "log4js": "^0.6.26",
    "method-override": "^2.3.3",
    "mojio-js": "^3.5.2",
    "mongodb": "^2.1.0-alpha",
    "mongoose": "^4.1.1",
    "msgpack-js": "^0.3.0",
    "multer": "^0.1.8",
    "mysql": "^2.8.0",
    "nconf": "^0.8.2",
    "nodemailer": "^2.2.1",
    "nodemailer-smtp-transport": "^2.4.1",
    "passport": "^0.3.2",
    "passport-local": "^1.0.0",
    "q": "^1.4.1",
    "qs": "^4.0.0",
    "query-types": "^0.1.4",
    "raw-body": "^2.1.1",
    "redis": "^0.12.1",
    "response-time": "^2.3.1",
    "sequelize": "3.24.3",
    "serve-favicon": "^2.3.0",
    "serve-index": "^1.7.0",
    "serve-static": "^1.10.0",
    "socket.io": "1.5.0",
    "socket.io-adapter": "^0.4.0",
    "socket.io-parser": "^2.2.6",
    "source-map-support": "^0.4.0",
    "st": "^0.5.4",
    "text-table": "^0.2.0",
    "uid2": "0.0.3",
    "umzug": "^1.8.0",
    "underscore": "^1.8.3",
    "vhost": "^3.0.1"

**Comment by stuartZhang** [comment]
I have traced the node-inspector program by console.log(...). I guess that the reason of the bug is to missing a folder "node-**v48**-linux-x64" under the directory "/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.1".

In my Linux box, the maximum node-version number is "node-**v47**-linux-x64".

**Comment by MasterJames** [comment]
Are people using some kind of alternative to this? is this project dead or obsolete?
Did that BM.length patch work or not? It's unclear without a proper PR submitted.

**Comment by MasterJames** [comment]
Here this does work despite the console error!
https://github.com/node-inspector/node-inspector/pull/938
Can someone reopen this or AT the right person to merge it, thanks?

**Comment by dacuotecuo** [comment]
my problem can also be solved like this :

Edit ...\node_modules\node-inspector\lib\InjectorClient.js file at line 111
if(NM.length > 0)
cb(error, NM[0].ref);

It works well!!!

**Comment by srkkhan** [comment]
same problem with node v6.9.1
anyone with perfect solution?

**Comment by MasterJames** [comment]
The patch in the PR works but just delete ininstall it and use the inregrated node --inspect flag. Further more you may use 6.3.1 to debug and then latest to deploy etc.
I've used this "n" tool to install vestions of nodejs which is another thing to consider and worth mentioning.

**Comment by iceprosurface** [comment]
Same issue with node v7.0.0 and Node Inspector v0.12.8
next time i will try node v6.3.1.

**Comment by iceprosurface** [comment]
```
my problem can also be solved like this :

Edit ...\node_modules\node-inspector\lib\InjectorClient.js file at line 111
if(NM.length > 0)
cb(error, NM[0].ref);

It works well!!!
```

It work in node v6.1.0 and Node Inspector v0.12.8,my OS is macos EI Caption(10.11).

**Comment by MasterJames** [comment]
There is more to that in the thread?!
1). Use the --inspect flag of node.
2). Insert the patch.

**Comment by jfbaquerocelis** [comment]
I have the same problem and I wrote the code in the line 111 of `~/node_modules/node-inspector/lib/InjectorClient.js`:

```javascript
  if(NM.length > 0)
    cb(error, NM[0].ref);
```

It's working!  :heart:

**Comment by ZinLeo** [comment]
i have same problem ,node v6.6.0  and node inspector v0.12.8
wrote the code in the line 111 of 
/usr/lib/node_modules/.node-inspector_npminstall/node_modules/.0.12.8@node-inspector/lib

`if(NM.length > 0)`

it's working!!!!!

**Comment by bertolo1988** [comment]
@ZinLeo send pull request please!

**Comment by c0bra** [comment]
+1

**Comment by miroslawmajka** [comment]
The aforementioned solutions do not work in my environment. Got this setup:
Node version: 6.9.1
Node Inspector version: 0.12.8

With the if-fix the debugger just stops and waits with an empty dev tools window in chrome.

Testing a very simple node module with one 'debugger' statement inside. This used to work with an older version of Node.js.

**Comment by D-soldier** [comment]
I use Node version 6.9.0 , Node Inspector Version 0.12.8 and os is Windows 10, have this problom

**Comment by sangwook-kim** [comment]
+1

**Comment by brownman** [comment]
https://github.com/tautologistics/node-inspector/blob/df67ad2d8568845b05cf78f667ee04217155c038/lib/InjectorClient.js

**Comment by martip-sainsburys** [comment]
I've tried the fix with node 6.9.1, the error disappears but the problem still remains since the console shows:

`Error: No NativeModule in target scope`

If the binary for node 48 is not there is not gonna work....

**Comment by gottfired** [comment]
I think node-inspector isn't updated anymore because node has that functionality built in now. Run node --inspect yourApp.js. This worked for me.

**Comment by wujunchuan** [comment]
node version 6.9.1 still broken

**Comment by ccqgithub** [comment]
node version 6.9.1 still broken

**Comment by errord** [comment]
node version 6.9.1 still broken me too

**Comment by wujunchuan** [comment]
@ccqgithub @errord 

Maybe node with higher version(6.9.1) built in inspect, and `node-inspect` don't update longer

**Comment by ccqgithub** [comment]
@wujunchuan that's true, very thanks ……

**Comment by bertolo1988** [comment]
@ccqgithub Use `node --inspect --debug-brk yourapp` to force the app to pause and wait so you have time to copy the chrome link.

**Comment by lovemybb** [comment]
This is a  syntax bug, why not fix it

**Comment by elliotatRetireup** [comment]
Same problem. Can't find a solution. Tried using node's built-in inspector. Opens the page but never shows any code. Any way to debug node?

**Comment by chandrajob365** [comment]
Downgrading from 6.9.1 to 6.3.1 worked for me too.
But still after so many releases , problem continues :( 👍

**Comment by ppalladino** [comment]
I am having the same issue. Using node v6.9.1 and node-inspector version v0.12.8

**Comment by Vlandmist** [comment]
@wujunchuan worked for me, on node 6.9.1. great

```
xxx@xyz MINGW64 /c/nodejs/projects/todo-app

$ node --inspect index.js
Debugger listening on port 9229.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=localhost:9229/b4f005c7-caad-4e7c-b554-5746da12b549
Server listening on 3000
Debugger attached.
```

**Comment by ppalladino** [comment]
@wujunchuan Worked like a charm! Thanks!!!

**Comment by kingnebby** [comment]
node 6.9.1 with node-inspector 0.12.8 on Ubuntu 16.04 was broken for me too.
Had to use nvm to switch to node 6.3.1 THEN install node-inspector, then it worked.
yowzers.

**Comment by scniro** [comment]
@elliotatRetireup I can't see code either, it's just, blank. Did you figure anything out?

**Comment by ccnixon** [comment]
Downgrading to 6.3.1 worked for me

**Comment by jonchenn** [comment]
@wujunchuan node --inspect app.js works well! Thanks!

**Comment by replete** [comment]
Why is this ticket closed? Still having this problem in node `6.9.2`.

**Comment by Elliot128** [comment]
@scniro 

Sorry its been a while. I had trouble using the node-inspect module, so I updated node to use the built-in v8 debugger released in [6.3.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#2016-07-06-version-630-current-fishrock123).

Using the v8 debugger, I then ran into an issue where the dev-tools were loading but no code was loading. This was because I had my hosts files mapping localhost to a different address than default. I changed this mapping and then `--inspect` or `--inspect --debug-brk` worked.

Further, it seems that there has been an update to node to resolve that problem I had with inspector in [6.9.2](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#2016-12-06-version-692-boron-lts-thealphanerd) by having inspector now prompt user to use 127.0.0.1 rather than localhost.

**Comment by replete** [comment]
@Elliott128 I have the issue with built in debugger (no code in chrome) and I haven't remapped localhost.

How is anyone debugging Node with both of these problems??? 

Switching node versions constantly is not practical

**Comment by jrgleason** [comment]
How does this new inspect work for things like mocha?

**Comment by jrgleason** [comment]
nm `mocha --debug-brk mocha-runner.js` worked

**Comment by Pierre-LoanJ** [comment]
Node 6.9.1 and node-inspector 0.12.8

 it works following these steps:
     1-  open a command prompt and run the following command:
	node-inspector --web-port=3030 (server app port)
     2- open another command prompt and run the following command:
	node --inspect --debug-brk server.js
     3- browse to the given URL in the second command prompt log on screen
     4- press F8 to make the server run
     5- eventually put some others breakpoints
     6- browse on another tab to your app (address and port defined in 1-)
     7- see server execution stops on breakpoints defined on step 5-

**Comment by wsrast** [comment]
node --inspect app.js is the correct answer. Many thanks to everyone who suggested it!

**Comment by ddg86** [comment]
I have set up the debugging after @Pierre-LoanJ description or I just use node --inspect app.js. Everything looks good so far. I can debug the first start in the app.js. But if I want to debug an endpoint with POSTMAN, I get the error "Cannot POST /api/trainingsWeek". The endpoint works if I don't debug.

Do I have to take another address? Or anoter tool than POSTMAN?

![first](https://cloud.githubusercontent.com/assets/25726457/22864836/f128370e-f158-11e6-827f-5e4f73e5e232.JPG)
![second](https://cloud.githubusercontent.com/assets/25726457/22864837/f12ae2a6-f158-11e6-90aa-de0a5ecb13c9.JPG)
![third](https://cloud.githubusercontent.com/assets/25726457/22864838/f141e42e-f158-11e6-8a03-b9acebd07d7a.JPG)

**Comment by BigPun86** [comment]
+1 for @ddg86

**Comment by suhailgupta03** [comment]
Same issue for node version 7.5.0

**Comment by juanlet** [comment]
same issue for node 6.9.2

**Comment by ddg86** [comment]
It is running. Maybe someone did the same stupid mistake. @BigPun86  @suhailgupta03  @juanlet 

I just used the wrong file and after some research my launch.json was buggy. I am working with Express now and the server set up and the Express set up is devided in two files app.js and www.js. You need to use the www.js as the starting point for debugging.

I use VS Code to debug. To get it running, open your project and the debug view. There should be no configuration available. Click on the little wheel -> choose node.js as the environment

![image](https://cloud.githubusercontent.com/assets/25726457/23062745/4eb9e032-f507-11e6-88dd-2d3af193f070.png)

After that the standard json will be created and looks like this.

![image](https://cloud.githubusercontent.com/assets/25726457/23062809/9930c98c-f507-11e6-86ab-ab0205d4b88e.png)

And then click on the play button with the selection start programm. With that the debugging should run. Now you can use POSTMAN with the same url when you just run your server and the debugger from VS Code should hit your breakpoint.

**Comment by majd-kho** [comment]
It was not working on Node v.7.6.0.
I did edit that @dacuotecuo recommended in the comments and it works now.

**Comment by tomccabe** [comment]
Same issue on 6.9.1; about the 6th time I've tried to use this tool over the last few years with exactly the same result. I've just moved on and using [devtool](https://github.com/Jam3/devtool) as it actually works.

**Comment by june07** [comment]
https://twitter.com/wesbos/status/839871649738555393

**Comment by ColinEberhardt** [comment]
Still b0rked on v6.10

**Comment by hustxiaoc** [comment]
@ColinEberhardt , have you tried `1.1.0`?

**Comment by peacechen** [comment]
Still fails with node-inspector 1.1.1
